// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Anguloso.Server.Models;

public partial class angulosodbContext : DbContext
{
    public angulosodbContext()
    {
    }

    public angulosodbContext(DbContextOptions<angulosodbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<biometrics> biometrics { get; set; }

    public virtual DbSet<client_diets> client_diets { get; set; }

    public virtual DbSet<clients> clients { get; set; }

    public virtual DbSet<config> config { get; set; }

    public virtual DbSet<diet_days> diet_days { get; set; }

    public virtual DbSet<diets> diets { get; set; }

    public virtual DbSet<food_sources> food_sources { get; set; }

    public virtual DbSet<foods> foods { get; set; }

    public virtual DbSet<food_exchange_groups> food_exchange_groups { get; set; }

    public virtual DbSet<meal_items> meal_items { get; set; }

    public virtual DbSet<meals> meals { get; set; }

    public virtual DbSet<recipe_items> recipe_items { get; set; }

    public virtual DbSet<recipes> recipes { get; set; }

    public virtual DbSet<users> users { get; set; }
    /*
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Database=dietexpressdb;Host=localhost;Username=admin;Password=Emperado;Persist Security Info=True");
    */
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<biometrics>(entity =>
        {
            entity.HasKey(e => e.id).HasName("biometrics_pkey");

            entity.HasOne(d => d.client).WithMany(p => p.biometrics)
                .HasForeignKey(d => d.client_id)
                .HasConstraintName("biometrics_client_id_fkey");
        });

        modelBuilder.Entity<client_diets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("client_diets_pkey");

            entity.HasIndex(e => e.client_id, "idx_unique_active_client_diet")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.assigned_at).HasDefaultValueSql("now()");
            entity.Property(e => e.is_active).HasDefaultValue(true);

            entity.HasOne(d => d.client).WithOne(p => p.client_diets)
                .HasForeignKey<client_diets>(d => d.client_id)
                .HasConstraintName("client_diets_client_id_fkey");

            entity.HasOne(d => d.diet).WithMany(p => p.client_diets)
                .HasForeignKey(d => d.diet_id)
                .HasConstraintName("client_diets_diet_id_fkey");
        });

        modelBuilder.Entity<clients>(entity =>
        {
            entity.HasKey(e => e.id).HasName("clients_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.email).HasMaxLength(150);
            entity.Property(e => e.full_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.gender).HasMaxLength(20);
            entity.Property(e => e.phone).HasMaxLength(50);

            entity.HasOne(d => d.user).WithMany(p => p.clients)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("clients_user_id_fkey");
        });

        modelBuilder.Entity<config>(entity =>
        {
            entity.HasKey(e => e.id).HasName("config_pkey");

            entity.Property(e => e.nombre_config).HasColumnType("character varying");
            entity.Property(e => e.valor_config).HasColumnType("character varying");
        });

        modelBuilder.Entity<diet_days>(entity =>
        {
            entity.HasKey(e => e.id).HasName("diet_days_pkey");

            entity.HasIndex(e => new { e.diet_id, e.day_index }, "diet_days_diet_id_day_index_key").IsUnique();

            entity.HasOne(d => d.diet).WithMany(p => p.diet_days)
                .HasForeignKey(d => d.diet_id)
                .HasConstraintName("diet_days_diet_id_fkey");
        });

        modelBuilder.Entity<diets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("diets_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.target_carbs).HasPrecision(6, 2);
            entity.Property(e => e.target_fat).HasPrecision(6, 2);
            entity.Property(e => e.target_kcal).HasPrecision(6, 2);
            entity.Property(e => e.target_protein).HasPrecision(6, 2);
        });

        modelBuilder.Entity<food_sources>(entity =>
        {
            entity.HasKey(e => e.id).HasName("food_sources_pkey");

            entity.Property(e => e.source_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.url).HasMaxLength(200);
        });

        modelBuilder.Entity<food_exchange_groups>(entity =>
        {
            entity.HasKey(e => e.id).HasName("food_exchange_groups_pkey");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.kcal).HasPrecision(6, 2);
            entity.Property(e => e.protein).HasPrecision(6, 2);
            entity.Property(e => e.carbs).HasPrecision(6, 2);
            entity.Property(e => e.fat).HasPrecision(6, 2);
        });

        modelBuilder.Entity<foods>(entity =>
        {
            entity.HasKey(e => e.id).HasName("foods_pkey");

            entity.HasIndex(e => e.external_id, "idx_foods_external")
                .IsUnique()
                .HasFilter("(external_id IS NOT NULL)");

            entity.Property(e => e.brands).HasMaxLength(200);
            entity.Property(e => e.category).HasMaxLength(200);
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.default_grams)
                .HasPrecision(6, 2)
                .HasDefaultValueSql("100");
            entity.Property(e => e.external_id).HasMaxLength(200);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.nutriscore).HasMaxLength(5);
            entity.Property(e => e.serving_size_text).HasMaxLength(50);
            entity.Property(e => e.serving_size_unit).HasMaxLength(10);
            entity.Property(e => e.source)
                .HasMaxLength(50)
                .HasDefaultValueSql("'local'::character varying");
            entity.Property(e => e.grams_per_exchange).HasPrecision(6, 2);

            entity.HasOne(d => d.exchange_group).WithMany(p => p.foods)
                .HasForeignKey(d => d.exchange_group_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("foods_exchange_group_id_fkey");
        });

        modelBuilder.Entity<meal_items>(entity =>
        {
            entity.HasKey(e => e.id).HasName("meal_items_pkey");

            entity.Property(e => e.carbs).HasPrecision(6, 2);
            entity.Property(e => e.fat).HasPrecision(6, 2);
            entity.Property(e => e.grams).HasPrecision(6, 2).IsRequired(false);
            entity.Property(e => e.kcal).HasPrecision(6, 2);
            entity.Property(e => e.protein).HasPrecision(6, 2);
            entity.Property(e => e.exchange_count).HasPrecision(6, 2);

            entity.HasOne(d => d.food).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.food_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("meal_items_food_id_fkey");

            entity.HasOne(d => d.exchange_group).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.exchange_group_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("meal_items_exchange_group_id_fkey");

            entity.HasOne(d => d.meal).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.meal_id)
                .HasConstraintName("meal_items_meal_id_fkey");
        });

        modelBuilder.Entity<meals>(entity =>
        {
            entity.HasKey(e => e.id).HasName("meals_pkey");

            entity.HasIndex(e => new { e.diet_day_id, e.meal_index }, "meals_diet_day_id_meal_index_key").IsUnique();

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.diet_day).WithMany(p => p.meals)
                .HasForeignKey(d => d.diet_day_id)
                .HasConstraintName("meals_diet_day_id_fkey");
        });

        modelBuilder.Entity<recipe_items>(entity =>
        {
            entity.HasKey(e => e.id).HasName("recipe_items_pkey");

            entity.Property(e => e.grams).HasPrecision(6, 2);

            entity.HasOne(d => d.food).WithMany(p => p.recipe_items)
                .HasForeignKey(d => d.food_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("recipe_items_food_id_fkey");

            entity.HasOne(d => d.recipe).WithMany(p => p.recipe_items)
                .HasForeignKey(d => d.recipe_id)
                .HasConstraintName("recipe_items_recipe_id_fkey");
        });

        modelBuilder.Entity<recipes>(entity =>
        {
            entity.HasKey(e => e.id).HasName("recipes_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.user).WithMany(p => p.recipes)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("recipes_user_id_fkey");
        });

        modelBuilder.Entity<users>(entity =>
        {
            entity.HasKey(e => e.id).HasName("users_pkey");

            entity.Property(e => e.country).HasMaxLength(100);
            entity.Property(e => e.email).HasColumnType("character varying");
            entity.Property(e => e.email_confirmed).HasDefaultValue(false);
            entity.Property(e => e.full_name).HasMaxLength(100);
            entity.Property(e => e.lang).HasMaxLength(20);
            entity.Property(e => e.password_hash).HasColumnType("character varying");
            entity.Property(e => e.role).HasMaxLength(20);
            entity.Property(e => e.username).HasMaxLength(50);
            entity.Property(e => e.clinic_name).HasMaxLength(150);
            entity.Property(e => e.clinic_address).HasMaxLength(250);
            entity.Property(e => e.clinic_phone).HasMaxLength(50);
            entity.Property(e => e.clinic_logo).HasColumnType("text");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
