// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Anguloso.Server.Models;

public partial class angulosodbContext : DbContext
{
    public angulosodbContext()
    {
    }

    public angulosodbContext(DbContextOptions<angulosodbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<biometrics> biometrics { get; set; }

    public virtual DbSet<client_diets> client_diets { get; set; }

    public virtual DbSet<clients> clients { get; set; }

    public virtual DbSet<medical_history> medical_history { get; set; }

    public virtual DbSet<digestive_health> digestive_health { get; set; }

    public virtual DbSet<food_preferences> food_preferences { get; set; }

    public virtual DbSet<lifestyle_history> lifestyle_history { get; set; }

    public virtual DbSet<config> config { get; set; }

    public virtual DbSet<diet_days> diet_days { get; set; }

    public virtual DbSet<diets> diets { get; set; }

    public virtual DbSet<food_sources> food_sources { get; set; }

    public virtual DbSet<foods> foods { get; set; }

    public virtual DbSet<food_favorites> food_favorites { get; set; }

    public virtual DbSet<food_exchange_groups> food_exchange_groups { get; set; }

    public virtual DbSet<meal_items> meal_items { get; set; }

    public virtual DbSet<meals> meals { get; set; }

    public virtual DbSet<recipe_items> recipe_items { get; set; }

    public virtual DbSet<recipes> recipes { get; set; }

    public virtual DbSet<users> users { get; set; }

    public virtual DbSet<tenants> tenants { get; set; }

    public virtual DbSet<audit_logs> audit_logs { get; set; }
    public virtual DbSet<subscription_plans> subscription_plans { get; set; }
    public virtual DbSet<subscription_plan_features> subscription_plan_features { get; set; }
    public virtual DbSet<subscriptions> subscriptions { get; set; }
    public virtual DbSet<client_nutritionist_assignments> client_nutritionist_assignments { get; set; }
    public virtual DbSet<subscription_events> subscription_events { get; set; }
    public virtual DbSet<subscription_payments> subscription_payments { get; set; }
    public virtual DbSet<payment_events> payment_events { get; set; }
    public virtual DbSet<invoices> invoices { get; set; }
    public virtual DbSet<invoice_lines> invoice_lines { get; set; }
    public virtual DbSet<fiscal_records> fiscal_records { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<biometrics>(entity =>
        {
            entity.HasKey(e => e.id).HasName("biometrics_pkey");

            entity.HasOne(d => d.client).WithMany(p => p.biometrics)
                .HasForeignKey(d => d.client_id)
                .HasConstraintName("biometrics_client_id_fkey");
        });

        modelBuilder.Entity<client_diets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("client_diets_pkey");

            entity.HasIndex(e => e.client_id, "idx_unique_active_client_diet")
                .IsUnique()
                .HasFilter("(is_active = true)");

            entity.Property(e => e.assigned_at).HasDefaultValueSql("now()");
            entity.Property(e => e.is_active).HasDefaultValue(true);

            entity.HasOne(d => d.client).WithMany(p => p.client_diets)
                .HasForeignKey(d => d.client_id)
                .HasConstraintName("client_diets_client_id_fkey");

            entity.HasOne(d => d.diet).WithMany(p => p.client_diets)
                .HasForeignKey(d => d.diet_id)
                .HasConstraintName("client_diets_diet_id_fkey");
        });

        modelBuilder.Entity<clients>(entity =>
        {
            entity.HasKey(e => e.id).HasName("clients_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.HasIndex(e => e.archived_at, "idx_clients_archived_at");
            entity.Property(e => e.email).HasMaxLength(150);
            entity.Property(e => e.full_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.gender).HasMaxLength(20);
            entity.Property(e => e.phone).HasMaxLength(50);

            entity.HasOne(d => d.user).WithMany(p => p.clients)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("clients_user_id_fkey");

            entity.HasOne(d => d.tenant).WithMany(p => p.clients)
                .HasForeignKey(d => d.tenant_id)
                .HasConstraintName("clients_tenant_id_fkey");
        });

        modelBuilder.Entity<medical_history>(entity =>
        {
            entity.HasKey(e => e.id).HasName("medical_history_pkey");

            entity.HasOne(d => d.client).WithOne(p => p.medical_history)
                .HasForeignKey<medical_history>(d => d.client_id)
                .HasConstraintName("medical_history_client_id_fkey");
        });

        modelBuilder.Entity<digestive_health>(entity =>
        {
            entity.HasKey(e => e.id).HasName("digestive_health_pkey");

            entity.HasOne(d => d.client).WithOne(p => p.digestive_health)
                .HasForeignKey<digestive_health>(d => d.client_id)
                .HasConstraintName("digestive_health_client_id_fkey");
        });

        modelBuilder.Entity<food_preferences>(entity =>
        {
            entity.HasKey(e => e.id).HasName("food_preferences_pkey");

            entity.HasOne(d => d.client).WithOne(p => p.food_preferences)
                .HasForeignKey<food_preferences>(d => d.client_id)
                .HasConstraintName("food_preferences_client_id_fkey");
        });

        modelBuilder.Entity<lifestyle_history>(entity =>
        {
            entity.HasKey(e => e.id).HasName("lifestyle_history_pkey");

            entity.HasOne(d => d.client).WithOne(p => p.lifestyle_history)
                .HasForeignKey<lifestyle_history>(d => d.client_id)
                .HasConstraintName("lifestyle_history_client_id_fkey");
        });

        modelBuilder.Entity<config>(entity =>
        {
            entity.HasKey(e => e.id).HasName("config_pkey");

            entity.Property(e => e.nombre_config).HasColumnType("character varying");
            entity.Property(e => e.valor_config).HasColumnType("character varying");
        });

        modelBuilder.Entity<diet_days>(entity =>
        {
            entity.HasKey(e => e.id).HasName("diet_days_pkey");

            entity.HasIndex(e => new { e.diet_id, e.day_index }, "diet_days_diet_id_day_index_key").IsUnique();

            entity.HasOne(d => d.diet).WithMany(p => p.diet_days)
                .HasForeignKey(d => d.diet_id)
                .HasConstraintName("diet_days_diet_id_fkey");
        });

        modelBuilder.Entity<diets>(entity =>
        {
            entity.HasKey(e => e.id).HasName("diets_pkey");

            entity.HasIndex(e => e.archived_at, "idx_diets_archived_at");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.target_carbs).HasPrecision(6, 2);
            entity.Property(e => e.target_fat).HasPrecision(6, 2);
            entity.Property(e => e.target_kcal).HasPrecision(6, 2);
            entity.Property(e => e.target_protein).HasPrecision(6, 2);

            entity.HasOne(d => d.user).WithMany(p => p.diets)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("diets_user_id_fkey");

            entity.HasOne(d => d.tenant).WithMany(p => p.diets)
                .HasForeignKey(d => d.tenant_id)
                .HasConstraintName("diets_tenant_id_fkey");
        });

        modelBuilder.Entity<food_favorites>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.HasIndex(e => new { e.user_id, e.food_id }).IsUnique();
            entity.HasOne(e => e.user).WithMany().HasForeignKey(e => e.user_id).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(e => e.food).WithMany().HasForeignKey(e => e.food_id).OnDelete(DeleteBehavior.Cascade);
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
        });

        modelBuilder.Entity<food_sources>(entity =>
        {
            entity.HasKey(e => e.id).HasName("food_sources_pkey");

            entity.Property(e => e.source_name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.url).HasMaxLength(200);
        });

        modelBuilder.Entity<food_exchange_groups>(entity =>
        {
            entity.HasKey(e => e.id).HasName("food_exchange_groups_pkey");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);

            entity.Property(e => e.kcal).HasPrecision(6, 2);
            entity.Property(e => e.protein).HasPrecision(6, 2);
            entity.Property(e => e.carbs).HasPrecision(6, 2);
            entity.Property(e => e.fat).HasPrecision(6, 2);
        });

        modelBuilder.Entity<foods>(entity =>
        {
            entity.HasKey(e => e.id).HasName("foods_pkey");

            entity.HasIndex(e => e.external_id, "idx_foods_external")
                .IsUnique()
                .HasFilter("(external_id IS NOT NULL)");

            entity.Property(e => e.brands).HasMaxLength(200);
            entity.Property(e => e.category).HasMaxLength(200);
            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.default_grams)
                .HasPrecision(6, 2)
                .HasDefaultValueSql("100");
            entity.Property(e => e.external_id).HasMaxLength(200);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.nutriscore).HasMaxLength(5);
            entity.Property(e => e.serving_size_text).HasMaxLength(50);
            entity.Property(e => e.serving_size_unit).HasMaxLength(10);
            entity.Property(e => e.source)
                .HasMaxLength(50)
                .HasDefaultValueSql("'local'::character varying");
            entity.Property(e => e.grams_per_exchange).HasPrecision(6, 2);

            entity.HasIndex(e => e.tenant_id, "idx_foods_tenant_id");
            entity.HasIndex(e => e.created_by_user_id, "idx_foods_created_by_user_id");

            entity.HasOne(d => d.tenant).WithMany()
                .HasForeignKey(d => d.tenant_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("foods_tenant_id_fkey");

            entity.HasOne(d => d.created_by_user).WithMany()
                .HasForeignKey(d => d.created_by_user_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("foods_created_by_user_id_fkey");

            entity.HasOne(d => d.exchange_group).WithMany(p => p.foods)
                .HasForeignKey(d => d.exchange_group_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("foods_exchange_group_id_fkey");
        });

        modelBuilder.Entity<meal_items>(entity =>
        {
            entity.HasKey(e => e.id).HasName("meal_items_pkey");

            entity.Property(e => e.carbs).HasPrecision(6, 2);
            entity.Property(e => e.fat).HasPrecision(6, 2);
            entity.Property(e => e.grams).HasPrecision(6, 2).IsRequired(false);
            entity.Property(e => e.kcal).HasPrecision(6, 2);
            entity.Property(e => e.protein).HasPrecision(6, 2);
            entity.Property(e => e.exchange_count).HasPrecision(6, 2);

            entity.HasOne(d => d.food).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.food_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("meal_items_food_id_fkey");

            entity.HasOne(d => d.exchange_group).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.exchange_group_id)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("meal_items_exchange_group_id_fkey");

            entity.HasOne(d => d.meal).WithMany(p => p.meal_items)
                .HasForeignKey(d => d.meal_id)
                .HasConstraintName("meal_items_meal_id_fkey");
        });

        modelBuilder.Entity<meals>(entity =>
        {
            entity.HasKey(e => e.id).HasName("meals_pkey");

            entity.HasIndex(e => new { e.diet_day_id, e.meal_index }, "meals_diet_day_id_meal_index_key").IsUnique();

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.diet_day).WithMany(p => p.meals)
                .HasForeignKey(d => d.diet_day_id)
                .HasConstraintName("meals_diet_day_id_fkey");
        });

        modelBuilder.Entity<recipe_items>(entity =>
        {
            entity.HasKey(e => e.id).HasName("recipe_items_pkey");

            entity.Property(e => e.grams).HasPrecision(6, 2);

            entity.HasOne(d => d.food).WithMany(p => p.recipe_items)
                .HasForeignKey(d => d.food_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("recipe_items_food_id_fkey");

            entity.HasOne(d => d.recipe).WithMany(p => p.recipe_items)
                .HasForeignKey(d => d.recipe_id)
                .HasConstraintName("recipe_items_recipe_id_fkey");
        });

        modelBuilder.Entity<recipes>(entity =>
        {
            entity.HasKey(e => e.id).HasName("recipes_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.user).WithMany(p => p.recipes)
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("recipes_user_id_fkey");
            
            entity.HasOne(d => d.tenant).WithMany()
                .HasForeignKey(d => d.tenant_id)
                .HasConstraintName("recipes_tenant_id_fkey");
        });

        modelBuilder.Entity<users>(entity =>
        {
            entity.HasKey(e => e.id).HasName("users_pkey");

            entity.Property(e => e.country).HasMaxLength(100);
            entity.Property(e => e.email).HasColumnType("character varying");
            entity.Property(e => e.email_confirmed).HasDefaultValue(false);
            entity.Property(e => e.full_name).HasMaxLength(100);
            entity.Property(e => e.lang).HasMaxLength(20);
            entity.Property(e => e.password_hash).HasColumnType("character varying");
            entity.Property(e => e.role).HasMaxLength(20);
            entity.Property(e => e.username).HasMaxLength(50);
            entity.Property(e => e.clinic_name).HasMaxLength(150);
            entity.Property(e => e.clinic_address).HasMaxLength(250);
            entity.Property(e => e.clinic_phone).HasMaxLength(50);
            entity.Property(e => e.clinic_logo).HasColumnType("text");

            entity.HasOne(d => d.tenant).WithMany(p => p.users)
                .HasForeignKey(d => d.tenant_id)
                .HasConstraintName("users_tenant_id_fkey");
        });

        modelBuilder.Entity<tenants>(entity =>
        {
            entity.HasKey(e => e.id).HasName("tenants_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.legal_name).IsRequired().HasMaxLength(200);
            entity.Property(e => e.trade_name).HasMaxLength(200);
            entity.Property(e => e.cif_nif).HasMaxLength(50);
            entity.Property(e => e.slug).IsRequired().HasMaxLength(100);
            entity.Property(e => e.status).HasMaxLength(50).HasDefaultValue("active");
            entity.Property(e => e.dpo_email).HasMaxLength(150);
            entity.Property(e => e.contact_email).HasMaxLength(150);
            entity.Property(e => e.contact_phone).HasMaxLength(50);
            entity.Property(e => e.address).HasMaxLength(300);
            entity.Property(e => e.logo_url).HasColumnType("text");
        });

        modelBuilder.Entity<subscription_events>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.Property(e => e.event_type).HasMaxLength(100).IsRequired();
            entity.Property(e => e.details).HasColumnType("text");
            entity.HasOne<subscriptions>().WithMany().HasForeignKey(e => e.subscription_id).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<subscription_plans>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.HasIndex(e => e.code).IsUnique();
            entity.Property(e => e.code).HasMaxLength(50).IsRequired();
            entity.Property(e => e.name).HasMaxLength(150).IsRequired();
            entity.Property(e => e.monthly_price).HasPrecision(10, 2);
            entity.Property(e => e.yearly_price).HasPrecision(10, 2);
        });

        modelBuilder.Entity<subscription_plan_features>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.HasIndex(e => new { e.plan_id, e.feature_code }).IsUnique();
            entity.Property(e => e.feature_code).HasMaxLength(100).IsRequired();
            entity.HasOne(e => e.plan).WithMany(p => p.features).HasForeignKey(e => e.plan_id).OnDelete(DeleteBehavior.Cascade);
        });

        modelBuilder.Entity<subscriptions>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.HasIndex(e => e.tenant_id).IsUnique();
            entity.HasOne(e => e.tenant).WithMany().HasForeignKey(e => e.tenant_id).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(e => e.plan).WithMany(p => p.subscriptions).HasForeignKey(e => e.plan_id).OnDelete(DeleteBehavior.Restrict);
        });

        modelBuilder.Entity<client_nutritionist_assignments>(entity =>
        {
            entity.HasKey(e => e.id);
            entity.HasIndex(e => e.client_id);
            entity.HasIndex(e => new { e.client_id, e.is_active }).IsUnique().HasFilter("is_active = true");
            entity.HasOne(e => e.client).WithMany().HasForeignKey(e => e.client_id).OnDelete(DeleteBehavior.Cascade);
            entity.HasOne(e => e.nutritionist).WithMany().HasForeignKey(e => e.nutritionist_id).OnDelete(DeleteBehavior.Restrict);
            entity.HasOne(e => e.assigned_by_user).WithMany().HasForeignKey(e => e.assigned_by_user_id).OnDelete(DeleteBehavior.SetNull);
        });

        modelBuilder.Entity<audit_logs>(entity =>
        {
            entity.HasKey(e => e.id).HasName("audit_logs_pkey");

            entity.Property(e => e.created_at).HasDefaultValueSql("now()");
            entity.Property(e => e.action).IsRequired().HasMaxLength(100);
            entity.Property(e => e.entity_name).IsRequired().HasMaxLength(100);
            entity.Property(e => e.entity_id).HasMaxLength(100);
            entity.Property(e => e.user_role).HasMaxLength(50);
            entity.Property(e => e.ip_address).HasMaxLength(50);
            entity.Property(e => e.user_agent).HasMaxLength(300);
            entity.Property(e => e.details).HasColumnType("text");

            entity.HasOne(d => d.tenant).WithMany()
                .HasForeignKey(d => d.tenant_id)
                .HasConstraintName("audit_logs_tenant_id_fkey");

            entity.HasOne(d => d.user).WithMany()
                .HasForeignKey(d => d.user_id)
                .HasConstraintName("audit_logs_user_id_fkey");

            entity.HasOne(d => d.client).WithMany()
                .HasForeignKey(d => d.client_id)
                .HasConstraintName("audit_logs_client_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
