// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class biometrics
{
    public int id { get; set; }

    public int client_id { get; set; }

    public DateOnly measurement_date { get; set; }

    public double? weight { get; set; }

    public double? height { get; set; }

    public double? body_fat { get; set; }

    public double? muscle_mass { get; set; }

    public double? visceral_fat { get; set; }

    public double? waist { get; set; }

    public double? hip { get; set; }

    public double? neck { get; set; }

    public double? triceps { get; set; }

    public double? abdomen { get; set; }

    public double? thigh { get; set; }

    public double? subscapular { get; set; }

    public double? suprailiac { get; set; }

    public double? biceps { get; set; }

    public double? chest { get; set; }

    public double? axilla { get; set; }

    public double? calf_skinfold { get; set; }

    public double? arm_perimeter { get; set; }

    public double? calf_perimeter { get; set; }

    public double? wrist_diameter { get; set; }

    public double? femur_diameter { get; set; }

    public double? humerus_diameter { get; set; }

    public string notes { get; set; }

    public virtual clients client { get; set; }
}