// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class client_diets
{
    public int id { get; set; }

    public int client_id { get; set; }

    public int diet_id { get; set; }

    public DateTime? assigned_at { get; set; }

    public DateOnly start_date { get; set; }

    public DateOnly? end_date { get; set; }

    public bool? is_active { get; set; }

    public string notes { get; set; }

    public virtual clients client { get; set; }

    public virtual diets diet { get; set; }
}