// El generador EF deja las anotaciones nullable en el archivo aunque desactive el contexto nullable.
// CS8669 no aporta información útil en este modelo generado.
#pragma warning disable CS8669
#nullable disable
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

#pragma warning disable CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
public partial class clients
#pragma warning restore CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
{
    public int id { get; set; }

    public int? user_id { get; set; }

    public string full_name { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public DateOnly? birth_date { get; set; }

    public string gender { get; set; }

    public string notes { get; set; }

    public DateTime? created_at { get; set; }

    public string access_token { get; set; }

    public string passcode_hash { get; set; }

    public DateTime? last_portal_access { get; set; }

    public DateTime? access_token_expires_at { get; set; }

    public DateTime? archived_at { get; set; }

    public string lifecycle_status { get; set; } = "pending_info";

    public DateTime? lifecycle_status_changed_at { get; set; }

    public DateTime? last_activity_at { get; set; }

    public int portal_token_version { get; set; } = 1;

    public DateTime? onboarding_consent_at { get; set; }

    public string onboarding_consent_version { get; set; }

    public int? tenant_id { get; set; }

    public virtual tenants? tenant { get; set; }

    public virtual ICollection<biometrics> biometrics { get; set; } = new List<biometrics>();

    public virtual ICollection<client_diets> client_diets { get; set; } = new List<client_diets>();

    public virtual users? user { get; set; }

    public virtual medical_history medical_history { get; set; }

    public virtual digestive_health digestive_health { get; set; }

    public virtual food_preferences food_preferences { get; set; }

    public virtual lifestyle_history lifestyle_history { get; set; }
}