// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class clients
{
    public int id { get; set; }

    public int user_id { get; set; }

    public string full_name { get; set; }

    public string email { get; set; }

    public string phone { get; set; }

    public DateOnly? birth_date { get; set; }

    public string gender { get; set; }

    public string notes { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<biometrics> biometrics { get; set; } = new List<biometrics>();

    public virtual client_diets client_diets { get; set; }

    public virtual users user { get; set; }

    public virtual medical_history medical_history { get; set; }

    public virtual digestive_health digestive_health { get; set; }

    public virtual food_preferences food_preferences { get; set; }

    public virtual lifestyle_history lifestyle_history { get; set; }
}