// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class diets
{
    public int id { get; set; }

    public string name { get; set; }

    public decimal? target_kcal { get; set; }

    public decimal? target_protein { get; set; }

    public decimal? target_carbs { get; set; }

    public decimal? target_fat { get; set; }

    public string notes { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<client_diets> client_diets { get; set; } = new List<client_diets>();

    public virtual ICollection<diet_days> diet_days { get; set; } = new List<diet_days>();
}