// El generador EF deja las anotaciones nullable en el archivo aunque desactive el contexto nullable.
// CS8669 no aporta información útil en este modelo generado.
#pragma warning disable CS8669
#nullable disable
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

#pragma warning disable CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
public partial class diets
#pragma warning restore CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
{
    public int id { get; set; }

    public string name { get; set; }

    public decimal? target_kcal { get; set; }

    public decimal? target_protein { get; set; }

    public decimal? target_carbs { get; set; }

    public decimal? target_fat { get; set; }

    public string notes { get; set; }

    public DateTime? created_at { get; set; }

    public int? user_id { get; set; }

    public int? tenant_id { get; set; }

    public bool is_shared { get; set; } = false;

    public bool is_template { get; set; } = false;

    public DateTime? archived_at { get; set; }

    public virtual users user { get; set; }

    public virtual tenants? tenant { get; set; }

    public virtual ICollection<client_diets> client_diets { get; set; } = new List<client_diets>();

    public virtual ICollection<diet_days> diet_days { get; set; } = new List<diet_days>();
}