// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class diet_days
{
    public int id { get; set; }

    public int diet_id { get; set; }

    public int day_index { get; set; }

    public virtual diets diet { get; set; }

    public virtual ICollection<meals> meals { get; set; } = new List<meals>();
}