// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class food_sources
{
    public int id { get; set; }

    public string source_name { get; set; }

    public string url { get; set; }
}