// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class foods
{
    public int id { get; set; }

    public string name { get; set; }

    public string brands { get; set; }

    public string category { get; set; }

    public string nutriscore { get; set; }

    public double? kcal { get; set; }

    public double? protein { get; set; }

    public double? carbs { get; set; }

    public double? fat { get; set; }

    public double? saturated_fat { get; set; }

    public double? fiber { get; set; }

    public double? sugar { get; set; }

    public double? salt { get; set; }

    public double? vitamin_a_ug { get; set; }

    public double? vitamin_c_mg { get; set; }

    public double? vitamin_d_ug { get; set; }

    public double? vitamin_e_mg { get; set; }

    public double? vitamin_b12_ug { get; set; }

    public double? folate_ug { get; set; }

    public double? calcium_mg { get; set; }

    public double? iron_mg { get; set; }

    public double? magnesium_mg { get; set; }

    public double? potassium_mg { get; set; }

    public double? zinc_mg { get; set; }

    public double? serving_size { get; set; }

    public string serving_size_unit { get; set; }

    public string serving_size_text { get; set; }

    public decimal? default_grams { get; set; }

    public string source { get; set; }

    public string external_id { get; set; }

    public DateTime? last_synced_at { get; set; }

    public DateTime? created_at { get; set; }

    public int? exchange_group_id { get; set; }

    public decimal? grams_per_exchange { get; set; }

    public virtual food_exchange_groups exchange_group { get; set; }

    public virtual ICollection<meal_items> meal_items { get; set; } = new List<meal_items>();

    public virtual ICollection<recipe_items> recipe_items { get; set; } = new List<recipe_items>();
}