// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class meals
{
    public int id { get; set; }

    public int diet_day_id { get; set; }

    public string name { get; set; }

    public int meal_index { get; set; }

    public virtual diet_days diet_day { get; set; }

    public virtual ICollection<meal_items> meal_items { get; set; } = new List<meal_items>();
}