// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class meal_items
{
    public int id { get; set; }

    public int meal_id { get; set; }

    public int? food_id { get; set; }

    public decimal? grams { get; set; }

    public decimal? kcal { get; set; }

    public decimal? protein { get; set; }

    public decimal? carbs { get; set; }

    public decimal? fat { get; set; }

    public int? exchange_group_id { get; set; }

    public decimal? exchange_count { get; set; }

    public virtual foods food { get; set; }

    public virtual food_exchange_groups exchange_group { get; set; }

    public virtual meals meal { get; set; }
}