// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class recipe_items
{
    public int id { get; set; }

    public int recipe_id { get; set; }

    public int food_id { get; set; }

    public decimal grams { get; set; }

    public virtual foods food { get; set; }

    public virtual recipes recipe { get; set; }
}