// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class recipes
{
    public int id { get; set; }

    public int user_id { get; set; }

    public string name { get; set; }

    public string instructions { get; set; }

    public DateTime? created_at { get; set; }

    public virtual ICollection<recipe_items> recipe_items { get; set; } = new List<recipe_items>();

    public virtual users user { get; set; }
}