// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

#pragma warning disable CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
public partial class recipes
#pragma warning restore CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
{
    public int id { get; set; }

    public int user_id { get; set; }

    public string name { get; set; }

    public string instructions { get; set; }

    public DateTime? created_at { get; set; }

    public int? tenant_id { get; set; }

    public virtual tenants? tenant { get; set; }

    public virtual ICollection<recipe_items> recipe_items { get; set; } = new List<recipe_items>();

    public virtual users user { get; set; }
}