// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

public partial class users
{
    public int id { get; set; }

    public string username { get; set; }

    public string full_name { get; set; }

    public string password_hash { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? last_login { get; set; }

    public string role { get; set; }

    public string email { get; set; }

    public bool? email_confirmed { get; set; }

    public string email_confirmation_token { get; set; }

    public string reset_password_token { get; set; }

    public DateTime? reset_token_expiration { get; set; }

    public string google_id { get; set; }

    public string provider { get; set; }

    public string country { get; set; }

    public string lang { get; set; }

    public string clinic_name { get; set; }

    public string clinic_address { get; set; }

    public string clinic_phone { get; set; }

    public string clinic_logo { get; set; }

    public virtual ICollection<clients> clients { get; set; } = new List<clients>();

    public virtual ICollection<recipes> recipes { get; set; } = new List<recipes>();
}
