// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Anguloso.Server.Models;

#pragma warning disable CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
public partial class users
#pragma warning restore CS8981 // El nombre de tipo solo contiene caracteres ASCII en minúsculas. Estos nombres pueden reservarse para el idioma.
{
    public int id { get; set; }

    public string username { get; set; }

    public string full_name { get; set; }

    public string password_hash { get; set; }

    public DateTime? created_at { get; set; }

    public DateTime? archived_at { get; set; }

    public DateTime? last_login { get; set; }

    public string role { get; set; }

    public string email { get; set; }

    public bool? email_confirmed { get; set; }

    public string email_confirmation_token { get; set; }

    public string reset_password_token { get; set; }

    public DateTime? reset_token_expiration { get; set; }

    public DateTime? email_confirmation_expires_at { get; set; }

    public int token_version { get; set; }

    public string google_id { get; set; }

    public string provider { get; set; }

    public string country { get; set; }

    public string lang { get; set; }

    public string clinic_name { get; set; }

    public string clinic_address { get; set; }

    public string clinic_phone { get; set; }

    public string clinic_logo { get; set; }

    public string subscription_plan { get; set; }

    public string subscription_status { get; set; }

    public DateTime? license_expires_at { get; set; }

    public int? max_clients_allowed { get; set; }

    public int? tenant_id { get; set; }

    public virtual tenants? tenant { get; set; }

    public virtual ICollection<clients> clients { get; set; } = new List<clients>();

    public virtual ICollection<recipes> recipes { get; set; } = new List<recipes>();

    public virtual ICollection<diets> diets { get; set; } = new List<diets>();
}
